[project]
name = 'Decentralized-Energy-Antimatter-Research'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collaboration-framework]
path = 'contracts/collaboration-framework.clar'
clarity_version = 2
epoch = 2.5

[contracts.commercialization-assessment]
path = 'contracts/commercialization-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
